site_name: Raider Aerospace Society Onboarding
site_description: Quickstart guides for joining one of our teams
site_url: https://raideraerospacesociety25-26.github.io/ras-handbook/
repo_url: https://github.com/RaiderAerospaceSociety25-26/ras-handbook
repo_name: ras25-26/ras-handbook

theme:
    name: material
    favicon: assets/favicon.ico
    icon:
        repo: fontawesome/brands/github
    logo: assets/ras-logo.svg
    features:
        - navigation.sections
        - navigation.top
        - navigation.footer
        - content.code.copy
        - content.tabs.link
        - search.suggest
        - search.highlight
        - header.autohide
        - announce.dismiss
    palette:
        - scheme: default
          primary: red
          accent: deep-orange
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: red
          accent: deep-orange
          toggle:
              icon: material/brightness-2
              name: Switch to light mode

nav:
    - Home: index.md
    - Getting Started:
          - Terminal Basics: getting-started/terminal.md
          - GitHub:
                - Account Setup: getting-started/github/account-setup.md
                - GitHub Website: getting-started/github/github.md
          - Git Basics: getting-started/git.md
          - VS Code: getting-started/vscode.md
          - PlatformIO: getting-started/platformio.md
    - Team Standards:
          - Branching: standards/branching.md
          - Commit Style: standards/commits.md
          - Pull Requests: standards/prs.md
          - Tooling: standards/tooling.md
    - Checklists:
          - New Member: checklists/new-member.md
          - Workstation Setup: checklists/workstation-setup.md
    - FAQ: faq.md

markdown_extensions:
    - admonition
    - toc:
          permalink: true
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji

plugins:
    - search
    - git-committers:
          repository: RaiderAerospaceSociety25-26/ras-handbook
          branch: main
    - print-site:
          add_to_navigation: false
          print_page_title: "Onboarding (Printable)"
