site_name: Team Onboarding
site_description: Quickstart guides for joining the team
site_url: https://<your-user-or-org>.github.io/<repo>
repo_url: https://github.com/<your-user-or-org>/<repo>

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started:
      - Git Basics: getting-started/git.md
      - GitHub Setup: getting-started/github.md
      - VS Code: getting-started/vscode.md
      - PlatformIO: getting-started/platformio.md
  - Team Standards:
      - Branching: standards/branching.md
      - Commit Style: standards/commits.md
      - Pull Requests: standards/prs.md
      - Tooling: standards/tooling.md
  - Checklists:
      - New Member: checklists/new-member.md
      - Workstation Setup: checklists/workstation-setup.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - print-site:
      add_to_navigation: false
      print_page_title: "Onboarding (Printable)"
