name: Publish Handbook
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site
        run: mkdocs build

      - name: Upload PDF (if plugin made one)
        uses: actions/upload-artifact@v4
        with:
          name: ras-handbook-pdf
          path: site/**/*.pdf
