name: Publish Handbook
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install mkdocs-material mkdocs-pdf-export-plugin
      - run: mkdocs build
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ras-handbook.pdf
          path: site/pdf/ras-handbook.pdf
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install mkdocs-material mkdocs-pdf-export-plugin
      - run: mkdocs gh-deploy --force
